export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const FETCH_CUSTOMER_FULFILLED = 'FETCH_CUSTOMER_FULFILLED';
export const FETCH_CUSTOMER_REJECTED = 'FETCH_CUSTOMER_REJECTED';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_FULFILLED = 'DELETE_CUSTOMER_FULFILLED';
export const DELETE_CUSTOMER_REJECTED = 'DELETE_CUSTOMER_REJECTED';
