export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUPS_FULFILLED = 'FETCH_GROUPS_FULFILLED';
export const FETCH_GROUPS_REJECTED = 'FETCH_GROUPS_REJECTED';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_CUSTOMER_FULFILLED = 'CREATE_CUSTOMER_FULFILLED';
export const CREATE_CUSTOMER_REJECTED = 'CREATE_CUSTOMER_REJECTED';
export const RESET_CREATE_CUSTOMER_STATUS = 'RESET_CREATE_CUSTOMER_STATUS';
