export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const FETCH_CUSTOMERS_FULFILLED = 'FETCH_CUSTOMERS_FULFILLED';
export const FETCH_CUSTOMERS_REJECTED = 'FETCH_CUSTOMERS_REJECTED';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_FULFILLED = 'DELETE_CUSTOMER_FULFILLED';
export const DELETE_CUSTOMER_REJECTED = 'DELETE_CUSTOMER_REJECTED';
